# Site settings
name: 海霞
location: 北京
company: 
position: UI工程师
github: https://github.com/
facebook: https://www.facebook.com/
phone: 1580424XXXX
email: xxxx@xxx.com

baseurl: ""
desingWorksUlr: "designworks.html"
permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

